### ISSUE TITLE
[Bug] Commented Out Python/Ruby/Bash Code in <CodeBlock> component is listed in 'On this Page' directory

### ISSUE THREAD

**Issue by mgregerson** [fern-api/fern#2671] opened 2024-01-19 22:37 UTC
### Describe the bug

When developing mdx pages, if one comments out code in a CodeBlock in a language that uses a hash to comment out code (ie Python), that line is added to the 'On this page' directory on the right side of the page. 

Additionally, future Headings (ie #) are not listed in 'On this page' directory after this bug occurs.

Note: This only occurs if there is more than one commented line of code in a CodeBlock.

### To reproduce

1. Create a new page in fern/docs/pages
2. Add a new Codeblock component with commented out code inside. For example:

```python
# fetch the dataset by ID
my_dataset = co.get_dataset("<DATASET_ID>")

# print each entry in the dataset
for record in my_dataset.open():
  print(record)

# save the dataset as jsonl
my_dataset.save_jsonl('./path/to/new/file.jsonl')
# or save the dataset as csv
my_dataset.save_csv('./path/to/new/file.csv')
```

This will add everything but the first commented line to our "On this page" directory.

### Expected behavior

Commented out code should not be added to the "On this page" directory.

### Screenshots

Image of above example:

<img width="252" alt="Screenshot 2024-01-19 at 5 35 23 PM" src="https://github.com/fern-api/fern/assets/105083434/ce3d1bda-e710-442e-ba6f-3a17dec2337d">

### Version
Fern Version: [e.g. 0.15.5; found in `fern.config.json`]

**Comment by minaelee** [comment] 2024-01-23 10:43
duplicate of https://github.com/fern-api/fern/issues/2593

**Comment by dannysheridan** [comment] 2024-01-25 00:31
closing as dup

**Closed by dannysheridan** 2024-01-25 00:31 UTC
