### ISSUE TITLE
[Bug] 'On this page' directory not identifying headers correctly after multiple <CodeBlock> components

### ISSUE THREAD

**Issue by mgregerson** [fern-api/fern#2689] opened 2024-01-22 18:25 UTC
### Describe the bug

When an mdx file has multiple <CodeBlock> components in succession, the following header is not added to our 'On this page' directory. 

### To reproduce

Create a new mdx file. 

Add the following to your markdown file:

```markdown
## 1. Set Up

First, let's install the SDK:

<CodeBlock title="python">
... sample codeblock
</CodeBlock>

Set up the Cohere client and import dependencies.

<CodeBlock title="python">
... sample codeblock
</CodeBlock>

## 2. Add Query and Documents
```

### Expected behavior

"1. Set Up" and "2. Add Query and Documents" should be included in our "On this page" directory. 

### Screenshots

<img width="265" alt="Screenshot 2024-01-22 at 1 24 27 PM" src="https://github.com/fern-api/fern/assets/105083434/4fed7b77-5758-4677-9c57-f1d51e30ff9d">

### Version
Fern Version: [e.g. 0.15.5; found in `fern.config.json`]

**Comment by minaelee** [comment] 2024-01-23 10:35
I tested and could not reproduce this - see https://ferntest4.docs.buildwithfern.com/ where multiple code blocks are used in succession yet all three headers show up in the 'On this page' panel. Tested with both fern-api@0.15.5 and 0.16.22.
Can you share your mdx file?

**Comment by mgregerson** [comment] 2024-01-23 13:28
Sure can. I've attached the file where I was getting this issue. 

[rerank-api.mdx.zip](https://github.com/fern-api/fern/files/14024586/rerank-api.mdx.zip)

**Comment by minaelee** [comment] 2024-01-24 01:09
I ran some tests and can duplicate your issue with the missing headers in the 'On this page' panel.

However, it does not seem to be caused by having multiple code blocks. From my testing, it appears to be caused specifically by having a `CodeBlock` with a blank line in it.

You can see my example at https://ferntest7.docs.buildwithfern.com, where I've gotten rid of the blank line in your MDX file's second `CodeBlock` beneath the first header, and the following (second) header shows up in 'On this page' . If I reintroduce that blank line, then the second header disappears again. 

To demonstrate further, since the `CodeBlock` beneath the 'Example Response' header contains blank lines, I've added a 'Test' header beneath that one to see if it would show up in 'On this page'. It doesn't. 

This is definitely a bug that seems to affect all Fern documentation. It can be seen in Fern's own docs. For example, see [the FastAPI boilerplate page](https://docs.buildwithfern.com/server-boilerplate/server-boilerplate/fast-api). The 'On this page' is missing the link to Step 2, and in Step 1, there's a CodeBlock with a blank line in it. @dannysheridan

For the time being @mgregerson , until the bug is fixed, you could do what I did in https://ferntest7.docs.buildwithfern.com/ and remove the blank line from the second `CodeBlock`. Not ideal but works temporarily.

PS. You might like to know that a couple of smart quotes have snuck into your MDX page in this line: ` The SDK will always return the text of the documents passed in with the result, but for visibility’s sake, we’ve beautified the output.` Nothing to do with this issue, but just in case you'd like to strip them out.

**Comment by minaelee** [comment] 2024-01-24 02:30
In Fern docs this bug affects:
https://docs.buildwithfern.com/generate-sd-ks/generators/type-script-node-js-sdk (**Never Throw Errors** not shown)
https://docs.buildwithfern.com/generate-docs/overview/writing-content (**Versions** not shown)
https://docs.buildwithfern.com/api-definition/openapi/open-api-extensions (**Audiences** not shown)

Let me emphasize that this is only an issue with code blocks with blank lines created using `CodeBlock`. Code blocks with blank lines using Markdown code fences do not present this issue.

**Comment by dannysheridan** [comment] 2024-02-01 21:06
This is now fixed!

**Closed by dannysheridan** 2024-02-01 21:06 UTC
Labels: fern docs
