### ISSUE TITLE
fern generate --local fails if docker is provided with Rancher Desktop or colima

### ISSUE THREAD

**Issue by looztra** [fern-api/fern#1998] opened 2023-08-02 12:45 UTC
Both with `MacOS + Rancher Desktop` and `Windows/WSL2 + Rancher Desktop`, we face the same issue when running `fern generate --local`:

The output of one of the docker container is:

```text
╰─»  docker logs 34bd99ddea8f
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/src/fern_python/generators/fastapi/cli.py", line 15, in <module>
    typer.run(main)
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 1050, in run
    app()
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/typer/core.py", line 716, in main
    return _main(
  File "/usr/local/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/src/fern_python/generators/fastapi/cli.py", line 11, in main
    cli.run()
  File "/src/fern_python/cli/generator_cli.py", line 23, in run
    config = GeneratorConfig.parse_file(self.path_to_config_json)
  File "pydantic/main.py", line 561, in pydantic.main.BaseModel.parse_file
  File "pydantic/parse.py", line 57, in pydantic.parse.load_file
  File "/usr/local/lib/python3.9/pathlib.py", line 1259, in read_bytes
    with self.open(mode='rb') as f:
  File "/usr/local/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
IsADirectoryError: [Errno 21] Is a directory: '/fern/config.json'
```

How to reproduce:

Install Rancher Desktop to provide "docker"

```bash
╰─»  fern generate --local --keepDocker --log-level debug
DEBUG 2023-08-02T12:35:08.822Z Running fern (fern-api@0.12.0)
...
DEBUG 2023-08-02T12:35:12.672Z [resource-mgr-tf-gcs]: fernapi/fern-openapi Wrote IR to: /tmp/fern-16105-YZnthBlkrxzD/tmp-16105-Um4Z5Rfg16Xl
DEBUG 2023-08-02T12:35:12.672Z [resource-mgr-tf-gcs]: fernapi/fern-postman Wrote IR to: /tmp/fern-16105-YZnthBlkrxzD/tmp-16105-yNVFCC0a8R8o
DEBUG 2023-08-02T12:35:12.673Z [resource-mgr-tf-gcs]: fernapi/fern-openapi Will write config.json to: /tmp/fern-16105-YZnthBlkrxzD/tmp-16105-4Yx9WFSNkak0
DEBUG 2023-08-02T12:35:12.673Z [resource-mgr-tf-gcs]: fernapi/fern-postman Will write config.json to: /tmp/fern-16105-YZnthBlkrxzD/tmp-16105-z7OF2hp72O16
DEBUG 2023-08-02T12:35:12.673Z [resource-mgr-tf-gcs]: fernapi/fern-openapi Will write output to: /tmp/fern-16105-YZnthBlkrxzD/tmp-16105-B3u6XgynvDTN
DEBUG 2023-08-02T12:35:12.674Z [resource-mgr-tf-gcs]: fernapi/fern-postman Will write output to: /tmp/fern-16105-YZnthBlkrxzD/tmp-16105-aRZq67NcbdFW
DEBUG 2023-08-02T12:35:12.705Z [resource-mgr-tf-gcs]: fernapi/fern-fastapi-server Wrote IR to: /tmp/fern-16105-YZnthBlkrxzD/tmp-16105-hh4BeYH3EBll
DEBUG 2023-08-02T12:35:12.705Z [resource-mgr-tf-gcs]: fernapi/fern-fastapi-server Will write config.json to: /tmp/fern-16105-YZnthBlkrxzD/tmp-16105-JbZ015mS3j42
DEBUG 2023-08-02T12:35:12.706Z [resource-mgr-tf-gcs]: fernapi/fern-fastapi-server Will write output to: /tmp/fern-16105-YZnthBlkrxzD/tmp-16105-WWrbMK65E39j
ERROR 2023-08-02T12:35:14.025Z [resource-mgr-tf-gcs]: fernapi/fern-postman Docker exited with a non-zero exit code.
DEBUG 2023-08-02T12:35:14.056Z [resource-mgr-tf-gcs]: fernapi/fern-postman Error: Docker exited with a non-zero exit code.
                                                                               at tryRunDocker (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544772:11)
                                                                               at runMicrotasks (<anonymous>)
                                                                               at processTicksAndRejections (node:internal/process/task_queues:96:5)
                                                                               at async runDocker (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544746:5)
                                                                               at async runGenerator (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544840:3)
                                                                               at async writeFilesToDiskAndRunGenerator (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544896:3)
                                                                               at async /home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544859:9
                                                                               at async TaskContextImpl.runInteractiveTask (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:530004:7)
                                                                               at async Promise.all (index 2)
                                                                               at async runLocalGenerationForWorkspace (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544854:19)
ERROR 2023-08-02T12:35:14.146Z [resource-mgr-tf-gcs]: fernapi/fern-openapi Docker exited with a non-zero exit code.
DEBUG 2023-08-02T12:35:14.146Z [resource-mgr-tf-gcs]: fernapi/fern-openapi Error: Docker exited with a non-zero exit code.
                                                                               at tryRunDocker (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544772:11)
                                                                               at runMicrotasks (<anonymous>)
                                                                               at processTicksAndRejections (node:internal/process/task_queues:96:5)
                                                                               at async runDocker (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544746:5)
                                                                               at async runGenerator (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544840:3)
                                                                               at async writeFilesToDiskAndRunGenerator (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544896:3)
                                                                               at async /home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544859:9
                                                                               at async TaskContextImpl.runInteractiveTask (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:530004:7)
                                                                               at async Promise.all (index 0)
                                                                               at async runLocalGenerationForWorkspace (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544854:19)
ERROR 2023-08-02T12:35:14.635Z [resource-mgr-tf-gcs]: fernapi/fern-fastapi-server Docker exited with a non-zero exit code.
DEBUG 2023-08-02T12:35:14.635Z [resource-mgr-tf-gcs]: fernapi/fern-fastapi-server Error: Docker exited with a non-zero exit code.
                                                                                      at tryRunDocker (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544772:11)
                                                                                      at runMicrotasks (<anonymous>)
                                                                                      at processTicksAndRejections (node:internal/process/task_queues:96:5)
                                                                                      at async runDocker (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544746:5)
                                                                                      at async runGenerator (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544840:3)
                                                                                      at async writeFilesToDiskAndRunGenerator (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544896:3)
                                                                                      at async /home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544859:9
                                                                                      at async TaskContextImpl.runInteractiveTask (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:530004:7)
                                                                                      at async Promise.all (index 1)
                                                                                      at async runLocalGenerationForWorkspace (/home/cfurmaniak/.asdf/installs/nodejs/16.18.1/lib/node_modules/fern-api/bundle.cjs:544854:19)
DEBUG 2023-08-02T12:35:14.636Z Checking if fern-api upgrade is available...
┌─
│ x  fernapi/fern-openapi
│ x  fernapi/fern-fastapi-server
│ x  fernapi/fern-postman
└─
```

The weirdest part is that if I run the container by myself, it works as expected:

```bash
docker container run -ti \
           -v /tmp/fern-16105-YZnthBlkrxzD/tmp-16105-JbZ015mS3j42:/fern/config.json:ro \
           -v /tmp/fern-16105-YZnthBlkrxzD/tmp-16105-hh4BeYH3EBll:/fern/ir.json:ro \
           -v /tmp/fern-16105-YZnthBlkrxzD/tmp-16105-WWrbMK65E39j:/fern/output \
           fernapi/fern-fastapi-server:0.3.7 /fern/config.json
```

successfully generates the files

Please note that this also fails is docker is provided thanks to Colima on a macOS

**Comment by csm-kb** [comment] 2023-09-01 08:41
Can confirm this on Windows with WSL2, with a good idea as to why there:
```sh
2023-09-01 02:32:50 Encountered error [Error: ENOENT: no such file or directory, open '\fern\config.json'] {
2023-09-01 02:32:50   errno: -2,
2023-09-01 02:32:50   code: 'ENOENT',
2023-09-01 02:32:50   syscall: 'open',
2023-09-01 02:32:50   path: '\\fern\\config.json'
2023-09-01 02:32:50 }
2023-09-01 02:32:50 node:internal/process/promises:288
2023-09-01 02:32:50             triggerUncaughtException(err, true /* fromPromise */);
2023-09-01 02:32:50             ^
2023-09-01 02:32:50 
2023-09-01 02:32:50 [Error: ENOENT: no such file or directory, open '\fern\config.json'] {
2023-09-01 02:32:50   errno: -2,
2023-09-01 02:32:50   code: 'ENOENT',
2023-09-01 02:32:50   syscall: 'open',
2023-09-01 02:32:50   path: '\\fern\\config.json'
2023-09-01 02:32:50 }
2023-09-01 02:32:50 
2023-09-01 02:32:50 Node.js v18.1.0
```
This is from `fernapi/fern-openapi:0.0.28` -- I think this is just an edge case of the images not handling cross-platform OS path separation, since the respective path libs don't expect to see those in their runtime env.

`fernapi/fern-python-sdk:0.4.0`
- `2023-09-01 02:32:52 FileNotFoundError: [Errno 2] No such file or directory: '\\fern\\config.json'`

`fernapi/fern-java-sdk:0.4.3`
- `2023-09-01 02:32:49 Caused by: java.io.FileNotFoundException: \fern\config.json (No such file or directory)`

`fernapi/fern-typescript-node-sdk:0.7.2` and `fernapi/fern-typescript-browser-sdk:0.7.2`
- `2023-09-01 02:32:51 [Error: ENOENT: no such file or directory, open '\fern\config.json'] {`

`fernapi/fern-go-sdk:0.4.0` and `fernapi/fern-go-model:0.4.0`
- `2023-09-01 02:32:48 failed to read generator configuration: open \fern\config.json: no such file or directory`

@looztra could you clarify the issue name to capture this?

@dsinghvi thoughts? Should we be filing this edge case against every single SDK generator repo, or is this top level sufficient?

**Comment by dsinghvi** [comment] 2023-09-01 12:10
@csm-kb top level issue should be sufficient -- the issue here is actually with our typescript CLI.

**Comment by csm-kb** [comment] 2023-09-01 19:18
> @csm-kb top level issue should be sufficient -- the issue here is actually with our typescript CLI.

Aha, cheers for that! Let me know if there's anything I can do to assist.

**Comment by dannysheridan** [comment] 2024-01-22 22:41
closing as this hasn't been reported since.

**Closed by dannysheridan** 2024-01-22 22:41 UTC

**Comment by larisoncarvalho** [comment] 2024-07-13 07:11
Facing this same issue on 0.31.24
```
❯ fern -v
(node:49523) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:49551) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
0.31.24
```

Docker container logs after running `fern generate --local --keepDocker`:
```
❯ docker ps -a
CONTAINER ID   IMAGE                                    COMMAND                  CREATED          STATUS                      PORTS                    NAMES
00fd946a15d3   fernapi/fern-typescript-node-sdk:0.9.5   "node /bundle.js /fe…"   13 seconds ago   Exited (1) 12 seconds ago                            hungry_bouman

❯ docker logs 00fd946a15d3
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open '/fern/config.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/fern/config.json'
}

Node.js v18.1.0
```

**Comment by mstade** [comment] 2024-08-18 17:57
@dannysheridan we're seeing the same issue as @larisoncarvalho reported above, for what it's worth.

**Comment by mstade** [comment] 2024-08-18 21:26
I believe this may be permissions related. Running with `--log-level debug` and doing an `ls -la` for the relevant paths reveals the permissions to be `-rw-------`. My guess is that whatever process Docker is running under doesn't actually have access to these paths, so the binds fail. I don't know how to verify this though, so it's just speculation at this point.

**Comment by mstade** [comment] 2024-08-18 21:53
I think I may have found the root cause, this line: https://github.com/fern-api/fern/blame/d625288d4cf8ef69f1cfab61fc8c32a92ea43702/packages/cli/generation/local-generation/docker-utils/src/runDocker.ts#L69

When looking at the `dockerode` docs, which seems to be the library used to interface with Docker, it links to these API reference docs: https://docs.docker.com/engine/api/v1.46/#tag/Container/operation/ContainerCreate

In those docs it states that `Binds` should be nested under `HostConfig`. I changed the code in my local fern cli bundle, at line 1305896, to this:

```js
HostConfig: {
  Binds: binds,
},
```

And it worked! Not sure how this isn't broken for everyone, maybe it's a magic combination of Docker versions or what not. Regardless, this is obviously not a workable solution because I can't rely on monkey patching a dependency.

I will try posting a PR, but I have no idea how to test and make sure this doesn't break everything for everyone else.

**Comment by mstade** [comment] 2024-08-18 21:55
Opened PR here: https://github.com/fern-api/fern/pull/4332

**Comment by SebastianStehle** [comment] 2024-08-20 07:59
I have a similar issue with Docker Desktop:

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open '\fern\config.json'] {
  errno: [33m-2[39m,
  code: [32m'ENOENT'[39m,
  syscall: [32m'open'[39m,
  path: [32m'\\fern\\config.json'[39m
}

Node.js v18.1.0
```

I am also confused why it uses `config.json` and not `fern.config.json`

**Comment by mstade** [comment] 2024-08-20 08:29
@SebastianStehle I too ran into this with Docker Desktop. The file name is a red herring, the `/fern/config.json` file is an internal detail to how the generator container is run, as far as I understand it. The issue is that the [bind mounts](https://docs.docker.com/engine/storage/bind-mounts/) aren't set properly. I submitted a PR (#4332) to fix this, and it was accepted just the other day. I also applied the fix locally by changing the bundle in the package downloaded by npm. You can read more details about this in [my previous comment](https://github.com/fern-api/fern/issues/1998#issuecomment-2295408719).

@dannysheridan also noted in my PR that they cut releases multiple times per week so the fix should make its way out in production shortly. 😊

**Comment by mstade** [comment] 2024-08-23 14:34
@looztra @SebastianStehle @csm-kb @larisoncarvalho I implemented a fix for this issue in #4332 and I've now confirmed this is also released in the CLI, so hopefully this should be resolved next time you update your fern dependency.

Thank you @dannysheridan and @dsinghvi for the swift review and release!

**Comment by SebastianStehle** [comment] 2024-08-25 09:12
I have the following error now: 

```
Generated serde layer.
Generated exports
Persisted typescript project to /tmp/tmp-1-qvLNZ7AS2lyG
/bundle.js:254185
            throw new Error("Filepath is not absolute: " + value);
                  ^

Error: Filepath is not absolute: \fern\output
    at Object.of (/bundle.js:254185:19)
    at SdkGeneratorCli.run (/bundle.js:254489:58)
    at async SdkGeneratorCli.runCli (/bundle.js:254447:9)

Node.js v18.1.0
```

Have you experienced something like that before? First I thought it is the path in my generators.yml, but nothing changed when I changed that to an absolute path.

**Comment by mstade** [comment] 2024-08-25 17:12
@SebastianStehle no I've not run into this I'm afraid. Given the output it looks like you got past the issue this thread was about at least, but this new one could be related. TBH, I've never gotten Fern to actually persist any project files like package.json etc, only the library code. (See #3257.)
