### ISSUE TITLE
Specify default values for a type

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#466] opened 2022-07-29 16:38 UTC
As a user, I'd like to specify default values for optional booleans. and maybe other optional primitives too.

**Comment by dannysheridan** [comment] 2022-10-19 22:43
This applies across types (not just Booleans as originally written).

**Comment by zachkirsch** [comment] 2022-12-13 21:25
Duplicate of https://github.com/fern-api/fern/issues/419

**Closed by zachkirsch** 2022-12-13 21:25 UTC
Labels: definition
